import 'package:catalog_app/components/product_card.dart';
import 'package:catalog_app/models/product_model.dart';
import 'package:catalog_app/services/api_service.dart';
import 'package:catalog_app/view/cart_screen.dart';
import 'package:catalog_app/view/product_detail_screen.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  List<Products> allProducts = [];
  bool isLoading = false;
  String errorMessage = "";
  ApiService apiService = ApiService();
  Set<int> cartIds = {};

  Future<void> loadData() async {
    try {
      setState(() {
        isLoading = true;
      });

      final Autogenerated response = await apiService.fetchProducts();

      setState(() {
        allProducts = response.products ?? [];
        isLoading = false;
      });
    } catch (e, s) {
      print("ERROR: $e");
      print("STACK: $s");

      setState(() {
        errorMessage = "Failed to load products";
        isLoading = false;
      });
    }
  }

  @override
  void initState() {
    super.initState();
    loadData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Container(
              height: 100,
              width: double.infinity,
              color: Colors.deepPurpleAccent[100],
              child: Padding(
                padding: const EdgeInsets.all(18.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      "Strawberry",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 28,
                        fontWeight: FontWeight.bold,
                        letterSpacing: -0.5,
                      ),
                    ),

                    IconButton(
                      onPressed: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => CartScreen(
                              products: allProducts,
                              cartIds: cartIds,
                            ),
                          ),
                        );
                      },
                      icon: Icon(Icons.shopping_bag_rounded),
                      iconSize: 30,
                      color: Colors.white,
                    ),
                  ],
                ),
              ),
            ),

            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(18.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SizedBox(height: 10),

                    Container(
                      decoration: BoxDecoration(
                        color: Color(0xFFF5F5F5),
                        borderRadius: BorderRadius.circular(14),
                      ),
                      child: TextField(
                        decoration: InputDecoration(
                          hintText: "Search for products or categories",
                          hintStyle: TextStyle(color: Colors.grey),
                          prefixIcon: Icon(
                            Icons.search,
                            color: Colors.deepPurpleAccent[100],
                            size: 28,
                          ),
                          contentPadding: EdgeInsets.symmetric(vertical: 16),
                          border: InputBorder.none,
                        ),
                      ),
                    ),

                    SizedBox(height: 12),

                    Container(
                      width: double.infinity,
                      height: 150,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(14),
                        image: DecorationImage(
                          image: NetworkImage(
                            'https://images.pexels.com/photos/7712476/pexels-photo-7712476.jpeg',
                          ),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),

                    SizedBox(height: 12),

                    Center(
                      child: Text(
                        "Products",
                        style: TextStyle(
                          fontSize: 24,
                          color: Colors.deepPurple[800],
                        ),
                      ),
                    ),

                    SizedBox(height: 12),

                    Expanded(
                      child: isLoading
                          ? Center(child: CircularProgressIndicator())
                          : errorMessage.isNotEmpty
                          ? Center(child: Text(errorMessage))
                          : allProducts.isEmpty
                          ? Center(child: Text("No products"))
                          : GridView.builder(
                              padding: EdgeInsets.all(18),
                              itemCount: allProducts.length,
                              gridDelegate:
                                  SliverGridDelegateWithFixedCrossAxisCount(
                                    crossAxisCount: 2,
                                    crossAxisSpacing: 10,
                                    mainAxisSpacing: 10,
                                    childAspectRatio: 0.7,
                                  ),
                              itemBuilder: (context, index) {
                                final product = allProducts[index];

                                return GestureDetector(
                                  onTap: () {
                                    Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                        builder: (context) =>
                                            ProductDetailScreen(
                                              product: product,
                                              cartIds: cartIds,
                                            ),
                                      ),
                                    );
                                  },

                                  child: ProductCard(product: product),
                                );
                              },
                            ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
