import 'dart:convert';

import 'package:catalog_app/models/product_model.dart';
import 'package:http/http.dart' as http;

class ApiService {
  Future<Autogenerated> fetchProducts() async {
    final response = await http.get(
      Uri.parse("https://dummyjson.com/products"),
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      return Autogenerated.fromJson(data);
    } else {
      throw Exception("Failed to load products");
    }
  }
}
